---
title: "dredge plume"
author: "Ross Cunning"
date: "9/5/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
# Set knitr options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE)

# Load packages
library(tidyverse)
library(janitor)
library(lubridate)
library(furrr)
library(gamm4)
library(MASS)
library(zoo)

# Convert logit to probability
logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}


# Define start and end of dredging (for plotting)
dredge.start.date <- as.Date("2013-11-20")                # NOAA sediment report April 2016, page 44
dredge.end.date <- as.Date("2015-03-16")                  # DCA report August 2015, page 3
```

# Import dredge plume data
```{r}
#plume <- readxl::read_xls(path = "data/CoralSitesMay2017_bbb.xls", sheet = "exclude_normal_plumes") %>%
plume <- readxl::read_xls(path = "data/dredge_plume.xls", sheet = "plume presence absence") %>%
  gather(date, plume, -NAME, -LATITUDE, -LONGITUDE, -idx) %>%
  clean_names() %>%
  mutate(site = as_factor(name),
         date = as_date(date),
         plume = as.logical(plume),
         reef = str_sub(site, 1, 2),
         dir  = str_sub(site, 3, 3),
         channel = if_else(grepl("C", site), "control", "channelside")) %>%
  filter(date > dredge.start.date, date < dredge.end.date)



plume <- plume %>%
  filter(!grepl("50", name), !grepl("75", name), !(grepl("00", name)))# %>%
  #distinct(name) %>% arrange(name) %>% print(n = nrow(.)) %>%
  #distinct(idx, date, reef, dir, channel, plume)

#plume %>% distinct(date, plume, reef, dir, channel)


ggplot(plume, aes(x = date, y = plume)) +
  facet_wrap(~ name) +
  geom_point()
```


```{r}
# Filter data to only includ unique pixels (no duplicates, e.g. if multiple sites were in the same pixel)
plume.f <- plume %>% distinct(idx, date, plume, reef, dir, channel)

# Fit GAMMs for each reef --- but ONLY USE MULTIPLE SITES IF DIFF PIXELS!
gamms1 <- plume.f %>%
  filter(reef %in% c("HB", "R2", "R3"), dir %in% c("N", "S")) %>%
  # For each reef and direction
  nest(-reef, -dir, -channel) %>%
  mutate(
    # Fit a binomial GAMM for sediment stress over time at channelside vs. control, site as random
    mod = future_map(data, ~ gam(plume ~ s(as.numeric(date)),
                                   #random = ~ (1|idx),   # use PIXEL as random factor - some sites are in same pixel
                                   family = "binomial", data = .)),
    # Get newdata frame for predict() using the appropriate range of weeks
    newdata = map(data, ~ expand.grid(date = as.numeric(min(.$date):max(.$date)),
                                      channel = c("channelside", "control"))),
    # Get fitted values from GAMM using newdata frame
    fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, type = "response")),
    # Get confidence intervals by simulation
    Rbeta = map(mod, ~ mvrnorm(n = 1000, coef(.), vcov(.))),
    Xp = map2(mod, newdata, ~ predict(object = .x, newdata = .y, type = "lpmatrix")),
    sim = map2(Xp, Rbeta, function(x, y) x %*% t(y)),
    lci = map(sim, ~ logit2prob(apply(., 1, quantile, 0.08))),
    uci = map(sim, ~ logit2prob(apply(., 1, quantile, 0.92)))
  )


gamm.fits <- gamms1 %>% 
  unnest(newdata, fit, lci, uci) %>%
  mutate(date = zoo::as.Date.numeric(date))

### Plot fitted models
ggplot(gamm.fits, aes(x = date, y = fit, color = channel)) +
  facet_grid(dir + channel ~ reef) +
  #geom_segment(data = sedtrap, aes(x = start, xend = end, 
  #                                 y = sedrate_mgcm2d, yend = sedrate_mgcm2d), alpha=0.4) +
  geom_ribbon(aes(ymin = lci, ymax = uci, linetype = NA), alpha = 0.2) + 
  geom_line(lwd = 1) +
  geom_vline(xintercept = c(dredge.start.date, dredge.end.date), linetype = 1, lwd = 0.25) +
  labs(x = "Date", y = "Probability dredge plume present") +
  geom_point(data = filter(plume, reef %in% c("HB", "R2", "R3"), dir %in% c("N", "S")),
             aes(y = as.numeric(plume)), pch = "|")

```

```{r}
# Summarize plume presence
plume.summ <- plume %>%
  group_by(reef, dir, channel) %>%
  summarise(nobs = n(), nyes = sum(plume), nno = nobs - nyes, pct = nyes / nobs)

save(plume, plume.summ, gamm.fits, file = "data/plume.RData")
```

# Reported metrics
```{r}

# Plume frequency in late 2013
gamm.fits %>%
  filter(date < "2014-01-01") %>%
  group_by(reef, dir, channel) %>%
  summarise(mean = mean(fit)) %>%
  arrange(-mean)

# Plume frequency in 2014 - 2015
gamm.fits %>%
  filter(date >= "2014-01-01") %>%
  group_by(reef, dir, channel) %>%
  summarise(mean = mean(fit)) %>%
  arrange(-mean)
```

