---
title: "sediment traps"
author: "Ross Cunning"
date: "7/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Load packages
library(furrr)
library(MASS)
library(tidyverse)
library(lubridate)
library(lsmeans)
library(gamm4)
library(lme4)

# Plan for parallel processing
plan(multiprocess)

# Define function to convert logit to probability
logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}

# Define start and end of dredging (for plotting)
dredge.start.date <- as.Date("2013-11-20")                # NOAA sediment report April 2016, page 44
dredge.end.date <- as.Date("2015-03-16")                  # DCA report August 2015, page 3
```

# Load sediment trap data
```{r}
load("data/sedtrap.RData")
```

# Plot sedimentation rate over time for each permanent monitoring site
```{r}
# Get average sedimentation rates for each permanent monitoring site
sedrate <- sedtrap %>%
  group_by(reef, dir, channel, site, middate) %>%
  summarise(meansed = mean(sedrate),
            meanfine = mean(finerate),
            sdsed = sd(sedrate),
            sdfine = sd(finerate),
            sesed = sdsed / sqrt(n()),
            sefine = sdfine / sqrt(n()))

# Plot average total sedimentation rates for each site
ggplot(sedrate, aes(x = middate, y = meansed)) +
  facet_wrap(~ site) +
  #geom_point(size = 1) +
  geom_errorbar(aes(ymin = meansed - sdsed, ymax = meansed + sdsed)) +
  geom_line() + 
  geom_vline(xintercept = c(dredge.start.date, dredge.end.date), linetype = 1, lwd = 0.25) +
  labs(title = "Total sediments", x = "Date", y = "Grams / day")

# Plot average fine sedimentation rates for each site
ggplot(sedrate, aes(x = middate, y = meanfine)) +
  facet_wrap(~ site) +
  #geom_point(size = 1) +
  geom_errorbar(aes(ymin = meanfine - sdfine, ymax = meanfine + sdfine)) +
  geom_line() + 
  geom_vline(xintercept = c(dredge.start.date, dredge.end.date), linetype = 1, lwd = 0.25) +
  labs(title = "Fine sediments", x = "Date", y = "Grams / day")
```

# Filter dataset
```{r}
sedtrap <- sedtrap %>%
  filter(site != "HBN1")             # Omit HBN1 because was "buried" and not monitored for a long time
                                     # Both here and in tagged coral data
```

# Plot sedimentation rate over time for each reef and direction
```{r}
# Get average sedimentation rates for each reef/direction
sedrate <- sedtrap %>%
  group_by(reef, dir, channel, start, end, middate) %>%
  summarise(meansed = mean(sedrate),
            meanfine = mean(finerate),
            sdsed = sd(sedrate),
            sdfine = sd(finerate),
            sesed = sdsed / sqrt(n()),
            sefine = sdfine / sqrt(n())) %>%
  ungroup()

# Plot total sediments
ggplot(sedrate, aes(x = middate, y = meansed, color = channel)) +
  facet_grid(dir ~ reef) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = meansed - sdsed, ymax = meansed + sdsed)) +
  geom_line() +
  labs(title = "Total sediments", x = "Date", y = "Grams / day")

# Plot fine sediments
ggplot(sedrate, aes(x = middate, y = meanfine, color = channel)) +
  facet_grid(dir ~ reef) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymin = meanfine - sdfine, ymax = meanfine + sdfine)) +
  geom_line() +
  labs(title = "Fine sediments", x = "Date", y = "Grams / day")
```

# GAM models

## Total sediments
```{r}
total.gamms.reef.dir <- sedtrap %>%
  nest(-reef, -dir, -channel) %>%   # Nest by reef and direction
  mutate(
    # Fit gamm by channel (in parallel)
    mod = future_map(data, 
            ~ gamm(sedrate ~ s(as.numeric(middate)),#, k = 16),
                   weights = duration, data = ., family = "poisson",
                   verbosePQL = FALSE)$gam),
    # Get newdata frame for predict() using the appropriate range of days
    newdata = map(data, ~ expand.grid(middate = as.numeric(min(.$middate):max(.$middate)))),
                                      #channel = c("channelside", "control"))),
    # Get fitted values from GAMM using newdata frame
    fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, 
                                       type = "link", se.fit = TRUE)$fit),
    se.fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, 
                                       type = "link", se.fit = TRUE)$se.fit),
    lci = map2(fit, se.fit, ~ .x - (1.96 * .y)),
    lcir = map2(mod, lci, ~ .x$family$linkinv(.y)),
    uci = map2(fit, se.fit, ~ .x + (1.96 * .y)),
    ucir = map2(mod, uci, ~ .x$family$linkinv(.y)),
    fitr = map2(mod, fit, ~ .x$family$linkinv(.y))
  )

total.gamms.reef.dir.fits <- total.gamms.reef.dir %>% 
  unnest(newdata, fitr, lcir, ucir) %>%
  mutate(middate = zoo::as.Date.numeric(middate))

### Plot fitted models
ggplot(total.gamms.reef.dir.fits, aes(x = middate, y = fitr, color = channel)) +
  facet_grid(dir ~ reef) +
  geom_segment(data = sedtrap, aes(x = start, xend = end, y = sedrate, yend = sedrate), alpha=0.4) +
  geom_ribbon(aes(ymin = lcir, ymax = ucir, linetype = NA), alpha = 0.2) + 
  geom_line(lwd = 1) +
  geom_vline(xintercept = c(dredge.start.date, dredge.end.date), linetype = 1, lwd = 0.25) +
  labs(title = "Total sediments", x = "Date", y = "Sedimentation rate")

# Integrate to get total sediment deposited
## For reef 3 control sites, the earliest sediment trap sample had a midpoint of january 10-11, 2014. This cuts out almost 2 months of data after dredging began 11/20/13 from other sites for which we do have information on sedimentation rates. Therefore, to avoid excluding this data, let's assume that the sedimentation rate at these sites from 11/20/13 until data are available is the same as the sedimentation rate at the beginning of data.
total.gamms.reef.dir.fits.complete <- total.gamms.reef.dir.fits %>%
  complete(nesting(reef, dir, channel), middate) %>%
  group_by(reef, dir, channel) %>%
  fill(fitr, lcir, ucir, .direction = "up") %>%
  ungroup()

total.depo <- total.gamms.reef.dir.fits.complete %>%
  filter(middate >= "2013-11-20",              # Filter from start of dredging
         middate <= "2015-03-23") %>%          # Filter up to a week after date dredging ended
  group_by(reef, dir, channel) %>%
  summarise(int_min = sum(lcir),
            int_fit = sum(fitr),
            int_max = sum(ucir))

ggplot(total.depo, aes(x = channel, y = int_fit, fill = channel)) +
  facet_grid(dir ~ reef) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = int_min, ymax = int_max), width = 0.25, lwd = 0.25) +
  labs(title = "Total sediment deposition 2013-11-20 to 2015-03-23",
       y = "Grams", x = "")
```


## Fine sediments
```{r}
fine.gamms.reef.dir <- sedtrap %>%
  nest(-reef, -dir, -channel) %>%   # Nest by reef and direction
  mutate(
    # Fit gamm by channel (in parallel)
    mod = future_map(data, 
            ~ gamm(finerate ~ s(as.numeric(middate)),#, k = 16),
                   weights = duration, data = ., family = "poisson",
                   verbosePQL = FALSE)$gam),
    # Get newdata frame for predict() using the appropriate range of days
    newdata = map(data, ~ expand.grid(middate = as.numeric(min(.$middate):max(.$middate)))),
                                      #channel = c("channelside", "control"))),
    # Get fitted values from GAMM using newdata frame
    fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, 
                                       type = "link", se.fit = TRUE)$fit),
    se.fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, 
                                       type = "link", se.fit = TRUE)$se.fit),
    lci = map2(fit, se.fit, ~ .x - (1.96 * .y)),
    lcir = map2(mod, lci, ~ .x$family$linkinv(.y)),
    uci = map2(fit, se.fit, ~ .x + (1.96 * .y)),
    ucir = map2(mod, uci, ~ .x$family$linkinv(.y)),
    fitr = map2(mod, fit, ~ .x$family$linkinv(.y))
  )

fine.gamms.reef.dir.fits <- fine.gamms.reef.dir %>% 
  unnest(newdata, fitr, lcir, ucir) %>%
  mutate(middate = zoo::as.Date.numeric(middate))

save(fine.gamms.reef.dir.fits, file = "data/sedtrap.fine.gamms.RData")

### Plot fitted models
ggplot(fine.gamms.reef.dir.fits, aes(x = middate, y = fitr, color = channel)) +
  facet_grid(dir ~ reef) +
  geom_segment(data=sedtrap, aes(x = start, xend = end, y = finerate, yend = finerate), alpha=0.4) +
  geom_ribbon(aes(ymin = lcir, ymax = ucir, linetype = NA), alpha = 0.2) + 
  geom_line(lwd = 1) +
  geom_vline(xintercept = c(dredge.start.date, dredge.end.date), linetype = 1, lwd = 0.25) +
  labs(title = "Fine sediments", x = "Date", y = "Sedimentation rate")

# Integrate to get total sediment deposited
## For reef 3 control sites, the earliest sediment trap sample had a midpoint of january 10-11, 2014. This cuts out almost 2 months of data after dredging began 11/20/13 from other sites for which we do have information on sedimentation rates. Therefore, to avoid excluding this data, let's assume that the sedimentation rate at these sites from 11/20/13 until data are available is the same as the sedimentation rate at the beginning of data.
fine.gamms.reef.dir.fits.complete <- fine.gamms.reef.dir.fits %>%
  complete(nesting(reef, dir, channel), middate) %>%
  group_by(reef, dir, channel) %>%
  fill(fitr, lcir, ucir, .direction = "up") %>%
  ungroup()

fine.depo <- fine.gamms.reef.dir.fits.complete %>%
  filter(middate >= "2013-11-20",              # Filter from start of dredging
         middate <= "2015-03-23") %>%          # Filter up to a week after date dredging ended
  group_by(reef, dir, channel) %>%
  summarise(int_min = sum(lcir),
            int_fit = sum(fitr),
            int_max = sum(ucir))

ggplot(fine.depo, aes(x = channel, y = int_fit, fill = channel)) +
  facet_grid(dir ~ reef) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = int_min, ymax = int_max), width = 0.25, lwd = 0.25) +
  labs(title = "Fine sediment deposition 2013-11-20 to 2015-03-23",
       y = "Grams", x = "")
```

## Coarse sediments
```{r}
coarse.gamms.reef.dir <- sedtrap %>%
  nest(-reef, -dir, -channel) %>%   # Nest by reef and direction
  mutate(
    # Fit gamm by channel (in parallel)
    mod = future_map(data, 
            ~ gamm(pmax(0, sedrate - finerate) ~ s(as.numeric(middate)),#, k = 16),
                   weights = duration, data = ., family = "poisson",
                   verbosePQL = FALSE)$gam),
    # Get newdata frame for predict() using the appropriate range of days
    newdata = map(data, ~ expand.grid(middate = as.numeric(min(.$middate):max(.$middate)))),
                                      #channel = c("channelside", "control"))),
    # Get fitted values from GAMM using newdata frame
    fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, 
                                       type = "link", se.fit = TRUE)$fit),
    se.fit = map2(mod, newdata, ~ predict(object = .x, newdata = .y, 
                                       type = "link", se.fit = TRUE)$se.fit),
    lci = map2(fit, se.fit, ~ .x - (1.96 * .y)),
    lcir = map2(mod, lci, ~ .x$family$linkinv(.y)),
    uci = map2(fit, se.fit, ~ .x + (1.96 * .y)),
    ucir = map2(mod, uci, ~ .x$family$linkinv(.y)),
    fitr = map2(mod, fit, ~ .x$family$linkinv(.y))
  )

coarse.gamms.reef.dir.fits <- coarse.gamms.reef.dir %>% 
  unnest(newdata, fitr, lcir, ucir) %>%
  mutate(middate = zoo::as.Date.numeric(middate))

### Plot fitted models
ggplot(coarse.gamms.reef.dir.fits, aes(x = middate, y = fitr, color = channel)) +
  facet_grid(dir ~ reef) +
  geom_segment(data=sedtrap, aes(x = start, xend = end, y = sedrate - finerate, yend = sedrate - finerate), alpha=0.4) +
  geom_ribbon(aes(ymin = lcir, ymax = ucir, linetype = NA), alpha = 0.2) + 
  geom_line(lwd = 1) +
  geom_vline(xintercept = c(dredge.start.date, dredge.end.date), linetype = 1, lwd = 0.25) +
  labs(title = "Coarse sediments", x = "Date", y = "Sedimentation rate")

# Integrate to get total sediment deposited
## For reef 3 control sites, the earliest sediment trap sample had a midpoint of january 10-11, 2014. This cuts out almost 2 months of data after dredging began 11/20/13 from other sites for which we do have information on sedimentation rates. Therefore, to avoid excluding this data, let's assume that the sedimentation rate at these sites from 11/20/13 until data are available is the same as the sedimentation rate at the beginning of data.
coarse.gamms.reef.dir.fits.complete <- coarse.gamms.reef.dir.fits %>%
  complete(nesting(reef, dir, channel), middate) %>%
  group_by(reef, dir, channel) %>%
  fill(fitr, lcir, ucir, .direction = "up") %>%
  ungroup()

coarse.depo <- coarse.gamms.reef.dir.fits.complete %>%
  filter(middate >= "2013-11-20",              # Filter from start of dredging
         middate <= "2015-03-23") %>%          # Filter up to a week after date dredging ended
  group_by(reef, dir, channel) %>%
  summarise(int_min = sum(lcir),
            int_fit = sum(fitr),
            int_max = sum(ucir))

ggplot(coarse.depo, aes(x = channel, y = int_fit, fill = channel)) +
  facet_grid(dir ~ reef) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = int_min, ymax = int_max), width = 0.25, lwd = 0.25) +
  labs(title = "Coarse sediment deposition 2013-11-20 to 2015-03-23",
       y = "Grams", x = "")
```

## Save sediment integrations as .RData
```{r}
save(total.depo, fine.depo, coarse.depo, file = "data/sed_deposited.RData")
```

