---
title: "Import and tidy CPCe data"
author: "Ross Cunning"
date: "6/3/2018"
output: html_document
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = normalizePath(".."))

# Load packages
library(tidyverse)
library(stringr)
library(lubridate)
library(readxl)
library(janitor)
```

# Import data

Data sheets include percentages of each category in each frame. Multiply these by number of points (excluding tape, wand, and shadow) per frame to get number of points of each category.

```{r}
# Find all file names ending in .xlsx 
files <- list.files(path = "data/CPCe", pattern = "^[^~].*.xlsx", 
                    recursive = TRUE, full.names = TRUE)

# Import and tidy data from each file
cpce <- data_frame(file = files) %>%
  # Extract original DCA CPCe data filepath from cell B4
  mutate(DCAfile = as.character(map(file, readxl::read_xlsx,      
                   sheet = "Data Summary", range = "B4", col_names = FALSE))) %>%
  # Read in data from rows 6 to 23 -- contains percent of each category for each frame
  mutate(data = map(file, readxl::read_xlsx, 
                    sheet = "Data Summary", range = cell_rows(6:23))) %>%
  # Transpose data so each category is a column, each frame a row
  mutate(data = map(data, ~ as_tibble(t(.)))) %>%
  # Set first row of transposed data to column names
  mutate(data = map(data, function(x) rename_at(x, vars(names(x)), funs(slice(x, 1))))) %>%
  # Remove first row (old column names)
  mutate(data = map(data, ~ slice(., -1))) %>%
  # Clean column names
  mutate(data = map(data, ~ janitor::clean_names(.))) %>%
  # Remove rows at end that summarize frames (has NA for number_of_frames)
  mutate(data = map(data, ~ filter(., !is.na(number_of_frames)))) %>%
  # Remove unneeded columns
  mutate(data = map(data, ~ select(., -c(1, 2, 4)))) %>%
  # Convert all columns to numeric
  mutate(data = map(data, ~ mutate_all(., funs(as.numeric)))) %>%
  # Convert all category colummns from percent to number of points of each category
  mutate(data = map(data, ~ mutate_at(., -1, funs(./100 * total_points_minus_tape_wand_shadow)))) %>%
  # Round all numbers to nearest whole number (some slightly different due to DCA rounding)
  mutate(data = map(data, ~ mutate_all(., funs(round)))) %>%
  # Remove first column (total number of points column) - all columns are now categories
  mutate(data = map(data, ~ select(., -1)))
```

# Add additional metadata (site and date)

Use information contained within the filenames to get site and date.

```{r}
# Add site, week, transect information
cpce <- cpce %>%
  mutate(basename = tools::file_path_sans_ext(basename(file))) %>%
  mutate(basename = gsub("CPCe.", "", basename)) %>%
  mutate(basename = gsub("-RR", "", basename)) %>%
  mutate(basename = gsub("-LR", "", basename)) %>%
  separate(basename, into = c("site", "week", "transect"), sep = "\ |_|-") %>%
  #mutate(weekn = str_extract(week, "[[:digit:]]{1,2}")) %>%
  mutate(reef = str_sub(site, 1, 2),
         dir  = str_sub(site, 3, 3),
         channel = if_else(grepl("C", site), "control", "channelside"))

# Add date information
# Use information from "POM PERM SITE INVENTORY (5 29 18).xlsx" to add date information
cpce <- cpce %>%
  mutate(date = case_when(
    # Baseline week 3 is a different date for reef 2 and reef 3
    week == "BW3" ~ case_when(reef == "R2" ~ as.Date("2013-11-25"),
                              reef == "R3" ~ as.Date("2013-12-23")),
    # Baseline week 4 is a different date for reef 2 and reef 3
    week == "BW4" ~ case_when(reef == "R2" ~ as.Date("2013-12-02"),
                              reef == "R3" ~ as.Date("2013-12-20")),
    # Compliance weeks are the same for all reefs, number of weeks since 2013-11-20
    grepl("^C", week) ~ as.Date("2013-11-20") + 
      dweeks(as.numeric(str_extract(week, "[[:digit:]]{1,2}"))),
    # Postconstruction weeks
    week == "PC3" ~ as.Date("2015-07-01"),
    # Impact assessment
    week == "IA" ~ as.Date("2016-08-20")     ### THESE DATES NEED CONFIRMATION
  ))

```

# Save as .RData object
```{r}
cpce <- cpce %>% unnest(data)

save(cpce, file = "data/cpce.RData")
```


