---
title: "Extensive coral mortality and critical habitat loss following dredging and their association with remotely-sensed sediment plumes"
output: html_document
---

### Authors: Ross Cunning, Rachel N. Silverstein, Brian B. Barnes, Andrew C. Baker
### Journal: Marine Pollution Bulletin
### Link: [https://doi.org/10.1016/j.marpolbul.2019.05.027](https://doi.org/10.1016/j.marpolbul.2019.05.027)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

-----

This site walks through the project's data analysis with code and output in rendered R Markdown documents. For access to all raw data and code, visit the Github repository at [github.com/jrcunning/pom-dredge](http://github.com/jrcunning/pom-dredge).

We also provide access to all public reports compiled by Dial Cordy and Associates, Florida Department of Environmental Protection (FDEP), and National Marine Fisheries Service (NMFS) related to the Port of Miami dredging project. Reports can be downloaded [here](https://github.com/jrcunning/pom-dredge/tree/master/reports).

## Data import and tidying

In these documents, raw data is imported and tidied into usable formats for downstream analysis.

##### [Sediment trap data](Rmd/tidy_sedtrap_data.html)

##### [Benthic cover (CPCe) data](Rmd/tidy_cpce_data.html)

##### [Tagged coral condition data](Rmd/tidy_tagged_corals.html)

##### [Coral count data](Rmd/tidy_count_data.html)

##### [Sediment depth data](Rmd/tidy_sed_depth_type.html)

-----

## Data analysis

These documents serve as records of data analysis including initial data exploration and plotting, and preliminary and intermediate analyses. As such, the labels and terminology found in some of the code and figures in these documents differ from what is presented in the final manuscript. For example, in initial analyses sites were coded as "channelside" or "control" based on the FDEP/DCA study design, but were subsequently recoded in final analyses according to distance from channel once it became clear that "control" sites were also impacted by dredging. Similarly, the benthic category "sand", as coded by DCA, is referred to as sediment in final analyses, and the reef names also change from "Hard Bottom", "Reef 2", and "Reef 3" (as coded by DCA), to "Nearshore Ridge", "Inner Reef", and "Outer Reef", respectively, to be consistent with published literature.

##### [Dredge plume presence](Rmd/dredge_plume.html)

##### [Sediment deposition](Rmd/sediment_trap.html)

##### [Sediment cover](Rmd/sed_cover.html)

##### [Sediment depth](Rmd/sed_depth.html)

##### [Sedimentation stress to tagged corals](Rmd/sed_stress.html)

##### [Partial mortality of tagged corals](Rmd/partial_mortality.html)

##### [Total mortality of tagged corals](Rmd/total_mortality.html)

##### [Scleractinian density](Rmd/scler_density.html) ([non-disease-susceptible only](Rmd/nonsus_scler_density.html))

##### [Predicted impacts from plume data](Rmd/plume_predictions.Rmd)

This document contains the final, formatted versions of all figures used in the manuscript (main text and supplementary).

##### [Final manuscript figures](Rmd/Figures.html)

-----

## Manuscript

##### [Manuscript](https://doi.org/10.1016/j.marpolbul.2019.05.027)

##### [Supplementary Information](Rmd/SupplementaryInfo.html)
